### ISSUE TITLE
Operadores basicas

### ISSUE THREAD

**Issue by Johnc-byte** [SistemasTecTlaxiaco/practica-de-operaciones-basicas-Johnc-byte#1]
[operacionesb.pdf](https://github.com/user-attachments/files/16841780/operacionesb.pdf)

**Comment by irwingsael** [comment]
portada: 25
Procedimiento:25
Figuras, ilustraciones, fotografías: 25
Resultados y conclusiones: 25
Calificación de la practica: 20

**Comment by Johnc-byte** [comment]
portada: 25
Procedimiento:17
Figuras, ilustraciones, fotografías: 25
Resultados y conclusiones: 25
Calificación de la práctica: 18/20
